# Generated by Django 5.1.1 on 2024-11-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Integration", "0004_charge_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("status_code", models.IntegerField()),
                ("request_headers", models.JSONField(blank=True, null=True)),
                ("request_body", models.JSONField(blank=True, null=True)),
                ("response_headers", models.JSONField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
