# Generated by Django 5.1.1 on 2024-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Integration", "0006_requestlog_response_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="response_status",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
