# Generated by Django 5.1.1 on 2024-11-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_id", models.CharField(max_length=70)),
                ("en_name", models.CharField(max_length=30)),
                ("ar_name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=10)),
                ("is_licensed", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("commercial_registration", "commercial_registration"),
                            ("freelancer", "freelancer"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bankName", models.CharField(max_length=40)),
                ("accountName", models.CharField(max_length=40)),
                ("accountNumber", models.CharField(max_length=40)),
                ("accountSwift", models.CharField(max_length=40)),
                ("accountIban", models.CharField(max_length=40)),
            ],
        ),
    ]
