# Generated by Django 5.1.1 on 2024-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_id", models.CharField(max_length=70)),
                ("amount", models.FloatField()),
                ("cuurency", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_id", models.CharField(max_length=70)),
            ],
        ),
    ]
