# Generated by Django 5.1.1 on 2024-11-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Integration", "0002_charge_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charge",
            old_name="cuurency",
            new_name="currency",
        ),
    ]
