# Generated by Django 5.1.1 on 2024-11-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Integration", "0003_rename_cuurency_charge_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="timestamp",
            field=models.IntegerField(null=True),
        ),
    ]
